### PR TITLE
Update sdk to work with waas 1.12

### LINKED ISSUE #87: Update SDK to work with waas 1.12
We need to update the current SDK to our new released WaaS version 1.12.

Make it compatible and check wsas changelogs what needs to be changed.

### PR DESCRIPTION
**Pull request by lenabl**
- update sdk to be compatible with waas 1.12

resolves #87

### CODE REVIEW

**Comment by christianemmert** [comment]
The `should read transaction events for a specific contract` test case in `ethereum-read.e2e.js` fails due to a problem in WaaS itself. The error occurs in https://github.com/Tangany/waas/blob/f5968e8a01ad17778ea00d61e10ef5ccd562224b/src/classes/anyblock/anyblock.ts#L294 because sometimes the `event.args["value.hex"]` that gets returned from Anyblock is not a string but an array of values. As such the check `value.startsWith("0x-")` throws the error `value.startsWith is not a function`.

**Comment by christianemmert** [comment]
> The `should read transaction events for a specific contract` test case in `ethereum-read.e2e.js` fails due to a problem in WaaS itself. The error occurs in https://github.com/Tangany/waas/blob/f5968e8a01ad17778ea00d61e10ef5ccd562224b/src/classes/anyblock/anyblock.ts#L294 because sometimes the `event.args["value.hex"]` that gets returned from Anyblock is not a string but an array of values. As such the check `value.startsWith("0x-")` throws the error `value.startsWith is not a function`.
> 
> @mazlinho does it make sense to create an issue for that bug?

A new [Issue](https://github.com/Tangany/waas/issues/1000) for WaaS was created. The e2e test case in the sdk was changed to fetch a `Transfer` event instead.

File: src/request.ts [hunk 1]
```diff
@@ -48,4 +52,78 @@ export class Request<TOutput extends Record<string, any>> implements IWaasMethod
...
+            } else {
+                url += `${key}=${value}`
+            }
+
+            if (i < entries.length) {
+                url += "&"
+                i++;
+            }
+        }
+        return url;
```
Comment (gpa) [inline src/request.ts:92]: Theoretically we need to encode values with `encodeURIComponent` but I think our allowed inputs range doesn't need encoding ☑️

**Review by gpa — CHANGES_REQUESTED** [review]

File: src/interfaces/common.ts [hunk 2]
```diff
@@ -74,9 +76,9 @@ export interface ISearchResponse extends IPaginationResponse {
         total: number;
     };
     // The object definition for "list" describes only the minimum content and needs to be overwritten depending on the resource.
-    list: {
+    list: ({
         links: IHateoasLink<string>[];
-    }[];
+    } | RequestStatus )[];
```
[the remark this answers is not in the document]
Comment (christianemmert) [reply src/interfaces/common.ts]: [d2ae7fd](https://github.com/Tangany/waas-js-sdk/pull/88/commits/d2ae7fd2c0f486c09175c1e0e541946bb19c596f)

File: readme.md [hunk 3]
```diff
@@ -334,10 +337,21 @@ For more examples check out the tests (e.g. [./test/*.e2e.js](./test/ethereum.e2
     const { hash } = status;
     // once it is confirmed, further details are available as output of the request
     if (process === "Completed") {
-        const { hash, blockNr, data, status } = output;
+        const { hash, blockNr, data, status, gas } = output;
     }
     // obtain the status of a given request id
     const anotherStatus = await api.request("a2e19473b9ec44cf97f71c9d4615e364").get();
+
+	const request = new Request(api);
```
[the remark this answers is not in the document]
Comment (christianemmert) [reply readme.md]: [d2ae7fd](https://github.com/Tangany/waas-js-sdk/pull/88/commits/d2ae7fd2c0f486c09175c1e0e541946bb19c596f)

File: src/iterables/auto-pagination/resource-iterable.spec.ts [hunk 4]
```diff
@@ -15,8 +15,9 @@ interface IIteratorValue {
 // Use a concrete implementation since abstract classes cannot be tested as such
 class TestResourceIterable extends ResourceIterable<ISearchResponse, IIteratorValue> {
     protected convertResponseItem(item: ISearchResponse["list"][0]): IIteratorValue {
+        assert((item as any).links)
```
[the remark this answers is not in the document]
Comment (christianemmert) [reply src/iterables/auto-pagination/resource-iterable.spec.ts]: [d2ae7fd](https://github.com/Tangany/waas-js-sdk/pull/88/commits/d2ae7fd2c0f486c09175c1e0e541946bb19c596f)

File: src/request.ts [hunk 5]
```diff
@@ -48,4 +52,78 @@ export class Request<TOutput extends Record<string, any>> implements IWaasMethod
...
+        }
+        for (const [key, value] of entries) {
+            if (Array.isArray(value) && value.length > 0) {
+                value.map((item, index) => {
+                    url += `${key}=${item}`
+                    if ((index + 1) < value.length) {
+                        url += "&"
+                    }
+                })
+            } else if (Object.prototype.toString.call(value) === '[object Date]') {
```
[the remark this answers is not in the document]
Comment (christianemmert) [reply src/request.ts]: [d2ae7fd](https://github.com/Tangany/waas-js-sdk/pull/88/commits/d2ae7fd2c0f486c09175c1e0e541946bb19c596f)

File: src/request.ts [hunk 6]
```diff
@@ -48,4 +52,78 @@ export class Request<TOutput extends Record<string, any>> implements IWaasMethod
...
+    /**
+     * Returns an asynchronous iterable to iterate **page by page** through the request statuses that matched the search parameters.
+     * @param [params] - Optional search parameters
+     * @param [options] - Additional options that do not affect the API request but the SDK-side processing
+     * @see [docs]{@link https://docs.tangany.com/#72b95742-6682-4dae-a802-4bbd504df9f4}
+     */
+    // tslint:disable-next-line:unified-signatures
+    public list(params?: IRequestSearchParams, options?: ISearchOptions): RequestPageIterable;
+
+    public list(params?: IRequestSearchParams, options?: ISearchOptions): Promise<IRequestStatusesResponse> | RequestPageIterable | RequestIterable {
```
[the remark this answers is not in the document]
Comment (christianemmert) [reply src/request.ts]: [d2ae7fd](https://github.com/Tangany/waas-js-sdk/pull/88/commits/d2ae7fd2c0f486c09175c1e0e541946bb19c596f)

File: src/waas.ts [hunk 7]
```diff
@@ -130,6 +132,7 @@ export const ethereumRecipientTypeSendAsync = t.compile({
  * @param options.bitcoinTxConfirmations - Amount of block confirmations required for Bitcoin balance outputs to be included in the total wallet balance calculation
  * @param options.bitcoinTxSpeed - Target amount of block confirmations for the transaction to be included to the Bitcoin network
  * @param options.bitcoinMaxFeeRate - Maximum allowed fee rate in satoshi per byte for a Bitcoin transaction
```
[the remark this answers is not in the document]
Comment (christianemmert) [reply src/waas.ts]: [d2ae7fd](https://github.com/Tangany/waas-js-sdk/pull/88/commits/d2ae7fd2c0f486c09175c1e0e541946bb19c596f)

File: test/request.e2e.js [hunk 8]
```diff
@@ -0,0 +1,63 @@
...
+				assert.ok(requestId.includes(item.requestId))
+			})
+		}
+	});
+
+	it("should list request after request", async function() {
+		const requestIterable = await request.list(config, {autoPagination: true});
+
+		for await (const request of requestIterable) {
+			assert.ok(requestId.includes(request.requestId))
```
[the remark this answers is not in the document]
Comment (christianemmert) [reply test/request.e2e.js]: [d2ae7fd](https://github.com/Tangany/waas-js-sdk/pull/88/commits/d2ae7fd2c0f486c09175c1e0e541946bb19c596f)

File: src/interfaces/common.ts [hunk 9]
```diff
@@ -69,14 +70,21 @@ export interface INodeStatus<T> {
  * API response object sent to the client as a search result.
  * It contains the number of results, an result array and pagination links.
  */
-export interface ISearchResponse extends IPaginationResponse {
+export interface ISearchResponse<T = any> extends IPaginationResponse {
```
Comment (gpa) [inline src/interfaces/common.ts:73]: Is this type accessible to package clients? If so, this would be theoretically a breaking change, not sure if we need to care about this case though, probably not. Also do we need the new interface`ISearchResponseWithLinks` ? seems like every extends overrides the list type anyway with links, for example `export interface IEventSearchResponse extends ISearchResponse {
    list: {
        event: string;
        links: IHateoasLink<"event">[];
    }[];
}`

Comment (christianemmert) [reply src/interfaces/common.ts:77]: `ISearchResponseWithLinks` is only used and overwritten by other interfaces which then are accessible to clients. So no breaking change.
[2deadc8](https://github.com/Tangany/waas-js-sdk/pull/88/commits/2deadc89b397c67a73479831da429bec97a84ade)

Comment (christianemmert) [reply src/interfaces/common.ts:77]: `ISearchResponseWithLinks` is only used and overwritten by other interfaces which then are accessible to clients. So no breaking change.
[2deadc8](https://github.com/Tangany/waas-js-sdk/pull/88/commits/2deadc89b397c67a73479831da429bec97a84ade)

**Review by gpa — APPROVED** [review]
